"""Pruebas del pool REAL psycopg_pool (Fase 4H).

Verifica contra PostgreSQL real: BEGIN/COMMIT/ROLLBACK, dos conexiones
independientes, pool con mínimo 2 conexiones y recuperación tras error.
La pila usada es la de producción (PgConnectionProxy sobre psycopg_pool real);
no se mockea psycopg ni las conexiones.
"""

import sqlite3

import pytest
from psycopg.pq import TransactionStatus

from tests_pg._helpers import make_pg_proxy

pytestmark = pytest.mark.pg_live

SCRATCH_TABLE = "scratch_pool_live"


def _create_scratch(proxy) -> None:
    proxy.execute(
        f"CREATE TABLE {SCRATCH_TABLE} "
        "(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, payload TEXT)"
    )
    proxy.commit()


def _drop_scratch(proxy) -> None:
    proxy.execute(f"DROP TABLE IF EXISTS {SCRATCH_TABLE}")
    proxy.commit()


def test_pool_real_tiene_al_menos_dos_conexiones(pg_pool):
    stats = pg_pool.get_stats()
    pool_size = stats.get("pool_size") or len(getattr(pg_pool, "pool", []))
    assert pool_size >= 2
    pids = set()
    for _ in range(2):
        proxy = make_pg_proxy(pg_pool)
        try:
            row = proxy.execute("SELECT pg_backend_pid() AS pid").fetchone()
            pids.add(row[0])
        finally:
            proxy.close()
    assert len(pids) == 2


def test_begin_real_abre_transaccion_y_commit_cierra(pg_pool):
    proxy = make_pg_proxy(pg_pool)
    try:
        assert proxy.info.transaction_status == TransactionStatus.IDLE
        proxy.execute("BEGIN IMMEDIATE")
        assert proxy.info.transaction_status in (
            TransactionStatus.INTRANS,
            TransactionStatus.ACTIVE,
        )
        proxy.commit()
        assert proxy.info.transaction_status == TransactionStatus.IDLE
    finally:
        proxy.close()


def test_commit_hace_visible_la_escritura(pg_pool):
    proxy_a = make_pg_proxy(pg_pool)
    proxy_b = make_pg_proxy(pg_pool)
    try:
        _create_scratch(proxy_a)
        proxy_a.execute("BEGIN IMMEDIATE")
        proxy_a.execute(f"INSERT INTO {SCRATCH_TABLE} (payload) VALUES (%s)", ("sin commit",))
        before = proxy_b.execute(f"SELECT COUNT(*) FROM {SCRATCH_TABLE}").fetchone()[0]
        assert before == 0
        proxy_a.commit()
        after = proxy_b.execute(f"SELECT COUNT(*) FROM {SCRATCH_TABLE}").fetchone()[0]
        assert after == 1
    finally:
        try:
            _drop_scratch(proxy_a)
        except Exception:
            proxy_a.rollback()
        proxy_b.close()
        proxy_a.close()


def test_rollback_revierte_la_escritura_pendiente(pg_pool):
    proxy_a = make_pg_proxy(pg_pool)
    proxy_b = make_pg_proxy(pg_pool)
    try:
        _create_scratch(proxy_a)
        proxy_a.execute("BEGIN IMMEDIATE")
        proxy_a.execute(f"INSERT INTO {SCRATCH_TABLE} (payload) VALUES (%s)", ("a",))
        proxy_a.execute("ROLLBACK")
        after = proxy_b.execute(f"SELECT COUNT(*) FROM {SCRATCH_TABLE}").fetchone()[0]
        assert after == 0
    finally:
        try:
            _drop_scratch(proxy_a)
        except Exception:
            proxy_a.rollback()
        proxy_b.close()
        proxy_a.close()


def test_escrituras_sin_commit_no_se_ven_entre_conexiones(pg_pool):
    proxy_a = make_pg_proxy(pg_pool)
    proxy_b = make_pg_proxy(pg_pool)
    try:
        _create_scratch(proxy_a)
        proxy_a.execute("BEGIN IMMEDIATE")
        proxy_a.execute(f"INSERT INTO {SCRATCH_TABLE} (payload) VALUES (%s)", ("a",))
        proxy_b.execute("BEGIN IMMEDIATE")
        proxy_b.execute(f"INSERT INTO {SCRATCH_TABLE} (payload) VALUES (%s)", ("b",))
        a_sees_b = proxy_a.execute(f"SELECT COUNT(*) FROM {SCRATCH_TABLE}").fetchone()[0]
        b_sees_a = proxy_b.execute(f"SELECT COUNT(*) FROM {SCRATCH_TABLE}").fetchone()[0]
        assert a_sees_b == 1
        assert b_sees_a == 1
        proxy_a.execute("ROLLBACK")
        proxy_b.execute("ROLLBACK")
        final = proxy_b.execute(f"SELECT COUNT(*) FROM {SCRATCH_TABLE}").fetchone()[0]
        assert final == 0
    finally:
        try:
            _drop_scratch(proxy_a)
        except Exception:
            proxy_a.rollback()
        proxy_b.close()
        proxy_a.close()


def test_dos_conexiones_son_pids_distintos(pg_pool):
    proxy_a = make_pg_proxy(pg_pool)
    proxy_b = make_pg_proxy(pg_pool)
    try:
        pid_a = proxy_a.execute("SELECT pg_backend_pid() AS pid").fetchone()[0]
        pid_b = proxy_b.execute("SELECT pg_backend_pid() AS pid").fetchone()[0]
        assert pid_a != pid_b
    finally:
        proxy_b.close()
        proxy_a.close()


def test_conexion_recuperable_despues_de_error_y_rollback(pg_pool):
    proxy = make_pg_proxy(pg_pool)
    try:
        proxy.execute("BEGIN IMMEDIATE")
        with pytest.raises(sqlite3.ProgrammingError):
            proxy.execute("SELECT * FROM tabla_inexistente_4123")
        assert proxy.info.transaction_status == TransactionStatus.INERROR
        proxy.execute("ROLLBACK")
        assert proxy.info.transaction_status == TransactionStatus.IDLE
        row = proxy.execute("SELECT 1 AS ok").fetchone()
        assert row[0] == 1
    finally:
        proxy.close()
