"""Cobertura del harness: el seed deja las secuencias IDENTITY sincronizadas.

Ni `migrations_pg/001_initial_schema.sql` ni `seed_standard_test_data()` relies on
`GENERATED BY DEFAULT AS IDENTITY` advancing when an explicit id is supplied, which
PostgreSQL does not do: `INSERT INTO roles (id, ...) VALUES (1..4)`,
`businesses (id=1)` and `services (id=1..3)` left their sequences at their initial
value. The next `INSERT` without `id` — for example `provision_business()` — then
generated an already-taken id and PostgreSQL replied
`duplicate key value violates unique constraint`.

These tests pin down harness behaviour, not application behaviour: they assert that
a generated id is free after the standard seed. They also cover the two edges the
sync must handle: a table seeded with explicit ids and an identity table left empty.
"""

import pytest
from psycopg import sql

from tests_pg._helpers import (
    apply_initial_schema,
    build_test_db_conninfo,
    connect_autocommit,
    create_test_database,
    drop_test_database,
    new_db_name,
    seed_standard_test_data,
)


@pytest.fixture
def seeded_database(pg_enabled: str):
    """Discardable database with the schema applied AND the standard seed run."""
    dbname = new_db_name()
    create_test_database(pg_enabled, dbname)
    conninfo = build_test_db_conninfo(pg_enabled, dbname)
    apply_initial_schema(conninfo)
    seed_standard_test_data(conninfo)
    try:
        yield conninfo
    finally:
        drop_test_database(pg_enabled, dbname)


@pytest.fixture
def schema_only_database(pg_enabled: str):
    """Discardable database with the schema applied and NO standard seed."""
    dbname = new_db_name()
    create_test_database(pg_enabled, dbname)
    conninfo = build_test_db_conninfo(pg_enabled, dbname)
    apply_initial_schema(conninfo)
    try:
        yield conninfo
    finally:
        drop_test_database(pg_enabled, dbname)


def _generar_id(conn, sql: str) -> int:
    """Inserts without `id` and returns the generated one."""
    return conn.execute(sql).fetchone()[0]


def test_businesses_seed_deja_la_secuencia_libre(seeded_database):
    """`businesses` is seeded with id=1; an insert without id must get a free id."""
    with connect_autocommit(seeded_database) as conn:
        nuevo = _generar_id(
            conn,
            "INSERT INTO businesses (name, slug, active, pending) "
            "VALUES ('Negocio Nuevo', 'negocio-nuevo', TRUE, FALSE) RETURNING id",
        )
        maximo = conn.execute("SELECT MAX(id) FROM businesses").fetchone()[0]
        total = conn.execute("SELECT COUNT(*) FROM businesses").fetchone()[0]
    assert total == 2
    assert maximo == nuevo
    assert nuevo != 1


def test_services_seed_deja_la_secuencia_libre(seeded_database):
    """`services` is seeded with ids 1..3; an insert without id must get a free id."""
    with connect_autocommit(seeded_database) as conn:
        nuevo = _generar_id(
            conn,
            "INSERT INTO services (name, price, duration, active, business_id) "
            "VALUES ('Servicio Nuevo', 1000, 30, TRUE, 1) RETURNING id",
        )
        maximo = conn.execute("SELECT MAX(id) FROM services").fetchone()[0]
    assert maximo == nuevo
    assert nuevo > 3


def test_roles_sembrados_por_el_schema_dejan_la_secuencia_libre(seeded_database):
    """`roles` is seeded by the schema itself (ids 1..4), not by the standard seed."""
    with connect_autocommit(seeded_database) as conn:
        nuevo = _generar_id(conn, "INSERT INTO roles (name) VALUES ('viewer') RETURNING id")
    assert nuevo == 5


def test_schema_only_sincroniza_roles_sin_ejecutar_el_seed(schema_only_database):
    """Schema alone must already hand out a free `roles` id (no seed executed).

    `pg_test_database`-style fixtures apply only the schema, so this is the path
    that must not depend on `seed_standard_test_data()` running afterwards.
    """
    with connect_autocommit(schema_only_database) as conn:
        sembrados = conn.execute("SELECT id, name FROM roles ORDER BY id").fetchall()
        nuevo = _generar_id(conn, "INSERT INTO roles (name) VALUES ('viewer') RETURNING id")
    assert sembrados == [(1, "owner"), (2, "admin"), (3, "staff"), (4, "customer")]
    assert nuevo == 5


def test_schema_only_sincroniza_todas_las_secuencias(schema_only_database):
    """Every identity sequence must be positioned past the rows that exist.

    Reads `last_value` from the sequence relation itself: unlike
    `pg_sequences.last_value` (NULL until the sequence is actually consumed),
    it reflects what `setval` wrote.
    """
    with connect_autocommit(schema_only_database) as conn:
        tablas = [
            row[0]
            for row in conn.execute(
                "SELECT table_name FROM information_schema.columns "
                "WHERE table_schema = 'public' AND column_name = 'id' "
                "AND is_identity = 'YES' ORDER BY table_name"
            ).fetchall()
        ]
        assert tablas, "el schema debe definir columnas IDENTITY"

        desincronizadas = []
        for tabla in tablas:
            secuencia = conn.execute(
                "SELECT pg_get_serial_sequence(%s, 'id')", (f"public.{tabla}",)
            ).fetchone()[0]
            maximo = conn.execute(
                sql.SQL("SELECT MAX(id) FROM {}").format(sql.Identifier(tabla))
            ).fetchone()[0]
            if not secuencia:
                continue
            if maximo is None:
                # Tabla vacía: la secuencia arrancará en 1, no hay nada que sincronizar.
                continue
            esquema, nombre = conn.execute(
                "SELECT n.nspname, c.relname FROM pg_class c "
                "JOIN pg_namespace n ON n.oid = c.relnamespace "
                "WHERE c.oid = %s::regclass",
                (secuencia,),
            ).fetchone()
            ultimo = conn.execute(
                sql.SQL("SELECT last_value FROM {}").format(sql.Identifier(esquema, nombre))
            ).fetchone()[0]
            if ultimo < maximo:
                desincronizadas.append((tabla, ultimo, maximo))
    assert desincronizadas == []


def test_tabla_identity_vacia_arranca_en_uno(seeded_database):
    """An identity table with no seeded rows must still hand out a valid id."""
    with connect_autocommit(seeded_database) as conn:
        assert conn.execute("SELECT COUNT(*) FROM users").fetchone()[0] == 0
        nuevo = _generar_id(
            conn,
            "INSERT INTO users (email, password_hash) "
            "VALUES ('nuevo@test.local', 'hash') RETURNING id",
        )
    assert nuevo == 1


def test_sync_no_altera_los_ids_sembrados(seeded_database):
    """The sync must move the sequences only: seeded ids and relations stay intact."""
    with connect_autocommit(seeded_database) as conn:
        negocios = conn.execute("SELECT id, slug FROM businesses ORDER BY id").fetchall()
        servicios = conn.execute("SELECT id, name FROM services ORDER BY id").fetchall()
        roles = conn.execute("SELECT id, name FROM roles ORDER BY id").fetchall()
    assert negocios == [(1, "el-corte")]
    assert servicios == [(1, "Corte"), (2, "Corte + barba"), (3, "Barba")]
    assert roles == [(1, "owner"), (2, "admin"), (3, "staff"), (4, "customer")]


def test_insercion_sin_id_no_choca_tras_el_seed(seeded_database):
    """Two consecutive generated inserts must both succeed (no duplicate key)."""
    with connect_autocommit(seeded_database) as conn:
        primero = _generar_id(
            conn,
            "INSERT INTO businesses (name, slug, active, pending) "
            "VALUES ('A', 'negocio-a', TRUE, FALSE) RETURNING id",
        )
        segundo = _generar_id(
            conn,
            "INSERT INTO businesses (name, slug, active, pending) "
            "VALUES ('B', 'negocio-b', TRUE, FALSE) RETURNING id",
        )
    assert segundo == primero + 1
