"""Pruebas de la Fase 4E: esquema PostgreSQL final (migrations_pg).

Verifican por conteo e inspeccion estatica que migrations_pg/001_initial_schema.sql
materializa el mismo esquema final que las 22 migraciones SQLite de migrations/
(business_knowledge_fts y artefactos del runner SQLite quedan fuera).

No requieren una instancia PostgreSQL: validan estructura y correspondencia.
"""

import re
from pathlib import Path

SCHEMA_PATH = Path(__file__).resolve().parent.parent / "migrations_pg" / "001_initial_schema.sql"

EXPECTED_TABLES = {
    "appointments",
    "audit_log",
    "business_knowledge",
    "business_settings",
    "business_users",
    "businesses",
    "conversation_analytics",
    "conversation_messages",
    "conversation_sessions",
    "invitations",
    "loyalty_accounts",
    "loyalty_settings",
    "notification_log",
    "password_reset_tokens",
    "platform_sessions",
    "platform_users",
    "points_ledger",
    "redemptions",
    "resources",
    "retention_actions",
    "rewards",
    "roles",
    "services",
    "sessions",
    "users",
    "weekly_schedules",
}

CREATE_TABLE_RE = re.compile(r"CREATE TABLE\s+(\w+)", re.IGNORECASE)


def _read_schema() -> str:
    return SCHEMA_PATH.read_text(encoding="utf-8")


def _norm(text: str) -> str:
    return re.sub(r"\s+", " ", text).lower()


def _code_only(text: str) -> str:
    """SQL sin lineas de comentario (--), para inspeccionar solo codigo."""
    return "\n".join(line for line in text.splitlines() if not line.strip().startswith("--"))


def _table_blocks(schema: str) -> dict[str, str]:
    blocks: dict[str, str] = {}
    current: str | None = None
    for line in schema.splitlines():
        match = CREATE_TABLE_RE.search(line)
        if match:
            current = match.group(1)
            blocks.setdefault(current, [])
        if current is not None:
            blocks[current].append(line)
    return {name: "\n".join(lines) for name, lines in blocks.items()}


def test_schema_file_exists():
    assert SCHEMA_PATH.is_file(), "migrations_pg/001_initial_schema.sql debe existir"


def test_schema_file_not_empty():
    assert len(_read_schema().strip()) > 1000, "el esquema no debe estar vacio"


def test_core_tables_present():
    schema = _read_schema()
    for table in ("appointments", "business_settings", "weekly_schedules", "services"):
        assert re.search(rf"CREATE TABLE\s+{table}\b", schema), f"falta {table}"


def test_table_inventory_matches_expected():
    found = {m.group(1) for m in CREATE_TABLE_RE.finditer(_read_schema())}
    assert found == EXPECTED_TABLES, f"inventario inesperado: {found ^ EXPECTED_TABLES}"


def test_primary_keys_use_identity():
    blocks = _table_blocks(_read_schema())
    for table in EXPECTED_TABLES:
        block = _norm(blocks[table])
        assert "id bigint generated by default as identity primary key" in block, (
            f"{table}: id debe ser BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        )


def test_foreign_keys_with_on_delete_cascade():
    schema = _read_schema()
    cascades = [
        ("rewards", "businesses"),
        ("redemptions", "businesses"),
        ("redemptions", "loyalty_accounts"),
        ("redemptions", "rewards"),
        ("retention_actions", "businesses"),
        ("business_knowledge", "businesses"),
        ("conversation_sessions", "businesses"),
        ("conversation_messages", "conversation_sessions"),
        ("conversation_analytics", "businesses"),
        ("invitations", "businesses"),
        ("invitations", "users"),
        ("platform_sessions", "platform_users"),
        ("password_reset_tokens", "users"),
        ("resources", "businesses"),
    ]
    for table, ref in cascades:
        assert re.search(
            rf"CREATE TABLE\s+{table}\b.*?REFERENCES\s+{ref}\(\s*id\s*\).*?ON DELETE CASCADE",
            schema,
            re.DOTALL | re.IGNORECASE,
        ), f"falta FK {table}.{ref} ON DELETE CASCADE"


def test_on_delete_set_null_present():
    schema = _read_schema()
    set_nulls = [
        ("redemptions", "users"),
        ("retention_actions", "users"),
        ("audit_log", "platform_users"),
        ("audit_log", "businesses"),
    ]
    for table, ref in set_nulls:
        assert re.search(
            rf"CREATE TABLE\s+{table}\b.*?REFERENCES\s+{ref}\(\s*id\s*\).*?ON DELETE SET NULL",
            schema,
            re.DOTALL | re.IGNORECASE,
        ), f"falta FK {table}.{ref} ON DELETE SET NULL"


def test_unique_constraints_present():
    schema = _read_schema()
    inline_text = [
        ("businesses", "slug"),
        ("roles", "name"),
        ("users", "email"),
        ("platform_users", "email"),
    ]
    for table, col in inline_text:
        assert re.search(
            rf"CREATE TABLE\s+{table}\b[^;]*?\b{col}\s+TEXT NOT NULL UNIQUE\b", schema, re.DOTALL
        ), f"falta UNIQUE en {table}.{col}"
    inline_bigint = [("business_settings", "business_id"), ("loyalty_settings", "business_id")]
    for table, col in inline_bigint:
        assert re.search(
            rf"CREATE TABLE\s+{table}\b[^;]*?\b{col}\s+BIGINT NOT NULL UNIQUE\b", schema, re.DOTALL
        ), f"falta UNIQUE en {table}.{col}"
    composite = [
        ("weekly_schedules", "business_id, day_of_week"),
        ("business_users", "user_id, business_id"),
        ("loyalty_accounts", "business_id, customer_phone"),
        ("rewards", "business_id, name"),
        ("redemptions", "business_id, idempotency_key"),
        ("resources", "business_id, name"),
        ("conversation_sessions", "business_id, customer_phone"),
        ("conversation_analytics", "business_id, question_hash"),
    ]
    for table, cols in composite:
        assert re.search(
            rf"CREATE TABLE\s+{table}\b[^;]*?UNIQUE\s*\(\s*{cols}",
            schema,
            re.DOTALL | re.IGNORECASE,
        ), f"falta UNIQUE({cols}) en {table}"


def test_check_constraints_present():
    schema = _read_schema()
    checks = [
        ("rewards", r"points_cost\s+INTEGER NOT NULL CHECK\s*\(points_cost\s*>\s*0\)"),
        ("redemptions", r"points_used\s+INTEGER NOT NULL CHECK\s*\(points_used\s*>\s*0\)"),
        (
            "redemptions",
            r"status\s+TEXT NOT NULL DEFAULT 'redeemed'\s*.{0,120}?CHECK\s*"
            r"\(status IN \('redeemed', 'cancelled'\)\)",
        ),
        (
            "retention_actions",
            r"action_type\s+TEXT NOT NULL CHECK\s*"
            r"\(action_type IN \('viewed', 'contacted', 'skipped'\)\)",
        ),
        (
            "business_knowledge",
            r"type\s+TEXT NOT NULL CHECK\s*\(type IN \('faq', 'instruction', 'policy'\)\)",
        ),
        (
            "conversation_messages",
            r"role\s+TEXT NOT NULL CHECK\s*\(role IN \('user', 'assistant', 'human', 'system'\)\)",
        ),
    ]
    for table, pattern in checks:
        assert re.search(rf"CREATE TABLE\s+{table}\b.*?" + pattern, schema, re.DOTALL), (
            f"falta CHECK en {table}: {pattern}"
        )


def test_secondary_indexes_present():
    schema = _read_schema()
    index_names = [
        "idx_schedules_business",
        "idx_services_business",
        "idx_resources_business",
        "idx_appointments_phone",
        "idx_appointments_date_status",
        "idx_appointments_status",
        "idx_appointments_business",
        "idx_appointments_management_token",
        "idx_business_users_business",
        "idx_sessions_user",
        "idx_platform_sessions_user",
        "idx_audit_log_business_created",
        "idx_audit_log_action",
        "idx_invitations_business",
        "idx_invitations_user",
        "idx_notification_log_business",
        "idx_loyalty_settings_business",
        "idx_loyalty_accounts_business_balance",
        "idx_redemptions_business_created",
        "idx_redemptions_account",
        "idx_points_ledger_account",
        "idx_points_ledger_business_created",
        "idx_retention_actions_business_created",
        "idx_retention_actions_phone",
        "idx_bk_business_type",
        "idx_bk_business_active",
        "idx_conv_sessions_business_status",
        "idx_conv_sessions_business_phone",
        "idx_conv_messages_session",
        "idx_conv_messages_needs_human",
        "idx_conv_analytics_business",
        "idx_password_reset_tokens_user",
        "idx_password_reset_tokens_hash",
    ]
    for name in index_names:
        assert re.search(rf"CREATE INDEX\s+{name}\b", schema), f"falta indice {name}"


def test_partial_indexes_present():
    schema = _read_schema()
    assert re.search(
        r"unique_confirmed_appointment_slot\b.*?COALESCE\(resource_id,\s*-1\).*?WHERE status = 'confirmed'",
        schema,
        re.DOTALL,
    ), "faltan COALESCE y WHERE en unique_confirmed_appointment_slot (022)"
    assert re.search(
        r"idx_points_ledger_earn_per_appointment\b.*?WHERE type = 'earn' AND appointment_id IS NOT NULL",
        schema,
        re.DOTALL,
    ), "falta indice parcial de idempotencia de puntos (009)"
    assert re.search(
        r"idx_conv_sessions_public_token\b.*?WHERE public_token IS NOT NULL", schema, re.DOTALL
    ), "falta indice parcial de public_token (019)"


def test_postgres_types_mapping():
    schema = _read_schema()
    assert re.search(r"CREATE TABLE\s+services\b.*?price\s+NUMERIC\(10,2\)", schema, re.DOTALL), (
        "services.price debe ser NUMERIC(10,2)"
    )
    assert re.search(
        r"CREATE TABLE\s+appointments\b.*?appointment_date\s+DATE\s+NOT NULL.*?appointment_time\s+TIME\s+NOT NULL",
        schema,
        re.DOTALL,
    ), "appointment_date DATE y appointment_time TIME"
    assert re.search(
        r"CREATE TABLE\s+retention_actions\b.*?last_completed_date\s+DATE\b", schema, re.DOTALL
    ), "retention_actions.last_completed_date debe ser DATE"
    assert re.search(
        r"CREATE TABLE\s+weekly_schedules\b.*?morning_start\s+TIME\b", schema, re.DOTALL
    ), "horarios semanales deben ser TIME"
    assert re.search(r"\bTIMESTAMPTZ\b", schema), "usa timestamps TIMESTAMPTZ"
    for flag in (
        "active",
        "revoked",
        "notifications_enabled",
        "is_open",
        "needs_human",
        "pending",
        "enabled",
    ):
        assert re.search(rf"\b{flag}\s+BOOLEAN\b", schema), f"{flag} debe ser BOOLEAN"


def test_no_fts5_artifacts():
    schema = _code_only(_read_schema())
    assert re.search(r"CREATE TABLE\s+business_knowledge\b", schema), (
        "business_knowledge debe existir"
    )
    assert "business_knowledge_fts" not in schema, "FTS queda fuera de la Fase 4E"
    assert not re.search(r"\bfts5\b", schema, re.IGNORECASE), "no debe haber FTS5"
    assert not re.search(r"CREATE VIRTUAL TABLE", schema, re.IGNORECASE), "no tablas virtuales"
    assert not re.search(r"CREATE TRIGGER", schema, re.IGNORECASE), "no triggers"
    assert "bk_fts" not in schema, "no triggers de sincronizacion FTS"


def test_no_sqlite_only_syntax():
    schema = _code_only(_read_schema())
    assert "AUTOINCREMENT" not in schema.upper(), "AUTOINCREMENT no es de PostgreSQL"
    assert not re.search(r"\bPRAGMA\b", schema, re.IGNORECASE), "PRAGMA no es de PostgreSQL"
    assert not re.search(r"\bINSERT\s+OR\b", schema, re.IGNORECASE), (
        "INSERT OR IGNORE/REPLACE no aplica"
    )
    assert not re.search(r"\bBEGIN IMMEDIATE\b", schema, re.IGNORECASE), "BEGIN IMMEDIATE no aplica"
    assert "datetime(" not in schema.lower(), "datetime('now') no es de PostgreSQL"
    assert "ALTER TABLE" not in schema.upper(), "esquema final: sin migraciones ADD COLUMN"


def test_identity_columns_allow_explicit_ids():
    schema = _read_schema()
    assert re.search(
        r"id\s+BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", schema, re.IGNORECASE
    ), "GENERATED BY DEFAULT (no ALWAYS) para permitir IDs explicitos (ETL)"


def test_roles_seed_present():
    schema = _read_schema()
    assert re.search(r"INSERT INTO roles \(id, name\) VALUES", schema, re.IGNORECASE), (
        "falta insert de roles"
    )
    for role_id, name in (("1", "owner"), ("2", "admin"), ("3", "staff"), ("4", "customer")):
        assert re.search(rf"{role_id},\s*'{name}'", schema), f"falta seed role {name}"
    assert re.search(r"ON CONFLICT \(name\) DO NOTHING", schema, re.IGNORECASE), (
        "el seed de roles debe ser idempotente (ON CONFLICT (name) DO NOTHING)"
    )


def test_appointments_carry_full_interval_and_resource():
    schema = _read_schema()
    block = _table_blocks(schema)["appointments"]
    for column in (
        "customer_email",
        "appointment_end",
        "duration",
        "management_token_hash",
        "resource_id",
        "business_id",
    ):
        assert re.search(rf"\b{column}\b", block), f"appointments debe tener {column}"
