"""
Registro de Blueprints y rutas de la aplicación.
"""

from routes.health import health_bp
from routes.public import index, business_index
from routes.auth import login, login_slug, logout, logout_slug
from routes.auth_public import forgot_password, registro, reset_password
from routes.superadmin import (
    superadmin_login,
    superadmin_logout,
    superadmin_panel,
    superadmin_audit,
    superadmin_negocios_crear,
    superadmin_negocios_detalle,
    superadmin_negocios_aprobar,
    superadmin_negocios_desactivar,
    superadmin_negocios_activar,
    superadmin_negocios_reinviar,
)
from routes.invitation import (
    staff_invitation,
    public_invitation,
    admin_usuarios_invitar_enlace,
)
from routes.admin import (
    admin,
    admin_slug,
    admin_save_service,
    admin_toggle_service,
    admin_update_business_settings,
    admin_save_weekly_schedule,
    admin_cancel_appointment,
    admin_update_appointment_status,
    admin_reschedule_appointment,
    admin_reschedule_appointment_with_resource,
    admin_create_appointment_manual,
    admin_usuarios,
    admin_usuarios_invitar,
    admin_usuarios_cambiar_rol,
    admin_usuarios_revocar,
    admin_fidelizacion,
    admin_fidelizacion_configuracion,
    admin_fidelizacion_ajustar,
    admin_fidelizacion_recalcular,
    admin_recompensas,
    admin_recompensa_estado,
    admin_recursos,
    admin_create_resource,
    admin_toggle_resource,
    admin_conocimiento,
    admin_conocimiento_crear,
    admin_conocimiento_editar,
    admin_conocimiento_eliminar,
    admin_conversaciones,
    admin_conversaciones_detalle,
    admin_conversaciones_resolver,
    admin_conversaciones_estado,
    admin_inteligencia,
    admin_inteligencia_oportunidades,
)


def register_blueprints(app):
    """Registra todos los blueprints y rutas en la aplicación Flask.

    Args:
        app: Instancia de Flask application.
    """
    from routes.health import health

    # Health - sin url_prefix, sin autenticación, sin tenant context
    app.add_url_rule(
        "/health",
        endpoint="health",
        view_func=health,
        methods=["GET"],
    )

    # Public routes - landing page y contexto de negocio
    app.add_url_rule(
        "/",
        endpoint="index",
        view_func=index,
        methods=["GET"],
    )
    app.add_url_rule(
        "/b/<slug>",
        endpoint="business_index",
        view_func=business_index,
        methods=["GET"],
    )

    # Auth routes - login, logout, session helpers
    # Registrados via add_url_rule() para preservar endpoint names globales
    # (login, login_slug, logout, logout_slug).
    # NOTA: Flask 3.x no permite Blueprint(''), por lo que auth_bp no se
    # registra como Blueprint. En su lugar, las views se registran directamente.
    app.add_url_rule(
        "/login",
        endpoint="login",
        view_func=login,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/b/<slug>/login",
        endpoint="login_slug",
        view_func=login_slug,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/logout",
        endpoint="logout",
        view_func=logout,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/logout",
        endpoint="logout_slug",
        view_func=logout_slug,
        methods=["POST"],
    )

    # Auth Public routes - forgot, reset, registro
    app.add_url_rule(
        "/forgot",
        endpoint="forgot_password",
        view_func=forgot_password,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/registro",
        endpoint="registro",
        view_func=registro,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/reset/<token>",
        endpoint="reset_password",
        view_func=reset_password,
        methods=["GET", "POST"],
    )

    # Superadmin routes - platform level
    app.add_url_rule(
        "/superadmin/login",
        endpoint="superadmin_login",
        view_func=superadmin_login,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/superadmin/logout",
        endpoint="superadmin_logout",
        view_func=superadmin_logout,
        methods=["POST"],
    )
    app.add_url_rule(
        "/superadmin",
        endpoint="superadmin_panel",
        view_func=superadmin_panel,
        methods=["GET"],
    )
    app.add_url_rule(
        "/superadmin/auditoria",
        endpoint="superadmin_audit",
        view_func=superadmin_audit,
        methods=["GET"],
    )
    app.add_url_rule(
        "/superadmin/negocios/crear",
        endpoint="superadmin_negocios_crear",
        view_func=superadmin_negocios_crear,
        methods=["POST"],
    )
    app.add_url_rule(
        "/superadmin/negocios/<int:business_id>",
        endpoint="superadmin_negocios_detalle",
        view_func=superadmin_negocios_detalle,
        methods=["GET"],
    )
    app.add_url_rule(
        "/superadmin/negocios/<int:business_id>/aprobar",
        endpoint="superadmin_negocios_aprobar",
        view_func=superadmin_negocios_aprobar,
        methods=["POST"],
    )
    app.add_url_rule(
        "/superadmin/negocios/<int:business_id>/desactivar",
        endpoint="superadmin_negocios_desactivar",
        view_func=superadmin_negocios_desactivar,
        methods=["POST"],
    )
    app.add_url_rule(
        "/superadmin/negocios/<int:business_id>/activar",
        endpoint="superadmin_negocios_activar",
        view_func=superadmin_negocios_activar,
        methods=["POST"],
    )
    app.add_url_rule(
        "/superadmin/negocios/<int:business_id>/reinviar",
        endpoint="superadmin_negocios_reinviar",
        view_func=superadmin_negocios_reinviar,
        methods=["POST"],
    )

    # Invitation routes - staff, public, admin panel
    app.add_url_rule(
        "/b/<slug>/invitacion-staff/<token>",
        endpoint="staff_invitation",
        view_func=staff_invitation,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/b/<slug>/invitacion/<token>",
        endpoint="public_invitation",
        view_func=public_invitation,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/admin/usuarios/invitar-enlace",
        endpoint="admin_usuarios_invitar_enlace",
        view_func=admin_usuarios_invitar_enlace,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/usuarios/invitar-enlace",
        endpoint="admin_usuarios_invitar_enlace",
        view_func=admin_usuarios_invitar_enlace,
        methods=["POST"],
    )

    # Admin routes - panel, configuration, services, appointments
    app.add_url_rule(
        "/admin",
        endpoint="admin",
        view_func=admin,
        methods=["GET"],
    )
    app.add_url_rule(
        "/b/<slug>/admin",
        endpoint="admin_slug",
        view_func=admin_slug,
        methods=["GET"],
    )
    app.add_url_rule(
        "/admin/servicios/guardar",
        endpoint="admin_save_service",
        view_func=admin_save_service,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/servicios/guardar",
        endpoint="admin_save_service",
        view_func=admin_save_service,
        methods=["POST"],
    )
    app.add_url_rule(
        "/admin/servicios/<int:service_id>/estado",
        endpoint="admin_toggle_service",
        view_func=admin_toggle_service,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/servicios/<int:service_id>/estado",
        endpoint="admin_toggle_service",
        view_func=admin_toggle_service,
        methods=["POST"],
    )
    app.add_url_rule(
        "/admin/configuracion",
        endpoint="admin_update_business_settings",
        view_func=admin_update_business_settings,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/configuracion",
        endpoint="admin_update_business_settings",
        view_func=admin_update_business_settings,
        methods=["POST"],
    )
    app.add_url_rule(
        "/admin/horarios/guardar",
        endpoint="admin_save_weekly_schedule",
        view_func=admin_save_weekly_schedule,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/horarios/guardar",
        endpoint="admin_save_weekly_schedule",
        view_func=admin_save_weekly_schedule,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/turnos/<int:appointment_id>/cancelar",
        endpoint="admin_cancel_appointment",
        view_func=admin_cancel_appointment,
        methods=["POST"],
    )
    app.add_url_rule(
        "/admin/turnos/<int:appointment_id>/estado",
        endpoint="admin_update_appointment_status",
        view_func=admin_update_appointment_status,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/turnos/<int:appointment_id>/estado",
        endpoint="admin_update_appointment_status",
        view_func=admin_update_appointment_status,
        methods=["POST"],
    )
    app.add_url_rule(
        "/admin/turnos/<int:appointment_id>/reprogramar",
        endpoint="admin_reschedule_appointment",
        view_func=admin_reschedule_appointment,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/turnos/<int:appointment_id>/reprogramar",
        endpoint="admin_reschedule_appointment",
        view_func=admin_reschedule_appointment,
        methods=["POST"],
    )
    app.add_url_rule(
        "/admin/turnos/<int:appointment_id>/reprogramar/con-recurso",
        endpoint="admin_reschedule_appointment_with_resource",
        view_func=admin_reschedule_appointment_with_resource,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/turnos/<int:appointment_id>/reprogramar/con-recurso",
        endpoint="admin_reschedule_appointment_with_resource",
        view_func=admin_reschedule_appointment_with_resource,
        methods=["POST"],
    )
    app.add_url_rule(
        "/admin/turnos/crear",
        endpoint="admin_create_appointment_manual",
        view_func=admin_create_appointment_manual,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/turnos/crear",
        endpoint="admin_create_appointment_manual",
        view_func=admin_create_appointment_manual,
        methods=["POST"],
    )

    # Admin usuarios / memberships
    app.add_url_rule(
        "/admin/usuarios",
        endpoint="admin_usuarios",
        view_func=admin_usuarios,
        methods=["GET"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/usuarios",
        endpoint="admin_usuarios",
        view_func=admin_usuarios,
        methods=["GET"],
    )
    app.add_url_rule(
        "/admin/usuarios/invitar",
        endpoint="admin_usuarios_invitar",
        view_func=admin_usuarios_invitar,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/usuarios/invitar",
        endpoint="admin_usuarios_invitar",
        view_func=admin_usuarios_invitar,
        methods=["POST"],
    )
    app.add_url_rule(
        "/admin/usuarios/<int:user_id>/rol",
        endpoint="admin_usuarios_cambiar_rol",
        view_func=admin_usuarios_cambiar_rol,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/usuarios/<int:user_id>/rol",
        endpoint="admin_usuarios_cambiar_rol",
        view_func=admin_usuarios_cambiar_rol,
        methods=["POST"],
    )
    app.add_url_rule(
        "/admin/usuarios/<int:user_id>/revocar",
        endpoint="admin_usuarios_revocar",
        view_func=admin_usuarios_revocar,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/usuarios/<int:user_id>/revocar",
        endpoint="admin_usuarios_revocar",
        view_func=admin_usuarios_revocar,
        methods=["POST"],
    )

    # Admin fidelizacion / loyalty
    app.add_url_rule(
        "/admin/fidelizacion",
        endpoint="admin_fidelizacion",
        view_func=admin_fidelizacion,
        methods=["GET"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/fidelizacion",
        endpoint="admin_fidelizacion",
        view_func=admin_fidelizacion,
        methods=["GET"],
    )
    app.add_url_rule(
        "/admin/fidelizacion/configuracion",
        endpoint="admin_fidelizacion_configuracion",
        view_func=admin_fidelizacion_configuracion,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/fidelizacion/configuracion",
        endpoint="admin_fidelizacion_configuracion",
        view_func=admin_fidelizacion_configuracion,
        methods=["POST"],
    )
    app.add_url_rule(
        "/admin/fidelizacion/<int:account_id>/ajustar",
        endpoint="admin_fidelizacion_ajustar",
        view_func=admin_fidelizacion_ajustar,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/fidelizacion/<int:account_id>/ajustar",
        endpoint="admin_fidelizacion_ajustar",
        view_func=admin_fidelizacion_ajustar,
        methods=["POST"],
    )
    app.add_url_rule(
        "/admin/fidelizacion/recalcular",
        endpoint="admin_fidelizacion_recalcular",
        view_func=admin_fidelizacion_recalcular,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/fidelizacion/recalcular",
        endpoint="admin_fidelizacion_recalcular",
        view_func=admin_fidelizacion_recalcular,
        methods=["POST"],
    )
    app.add_url_rule(
        "/admin/fidelizacion/recompensas",
        endpoint="admin_recompensas",
        view_func=admin_recompensas,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/fidelizacion/recompensas",
        endpoint="admin_recompensas",
        view_func=admin_recompensas,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/admin/fidelizacion/recompensas/<int:reward_id>/estado",
        endpoint="admin_recompensa_estado",
        view_func=admin_recompensa_estado,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/fidelizacion/recompensas/<int:reward_id>/estado",
        endpoint="admin_recompensa_estado",
        view_func=admin_recompensa_estado,
        methods=["POST"],
    )

    # Admin recursos
    app.add_url_rule(
        "/admin/recursos",
        endpoint="admin_recursos",
        view_func=admin_recursos,
        methods=["GET"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/recursos",
        endpoint="admin_recursos",
        view_func=admin_recursos,
        methods=["GET"],
    )
    app.add_url_rule(
        "/admin/recursos/crear",
        endpoint="admin_create_resource",
        view_func=admin_create_resource,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/recursos/crear",
        endpoint="admin_create_resource",
        view_func=admin_create_resource,
        methods=["POST"],
    )
    app.add_url_rule(
        "/admin/recursos/<int:resource_id>/estado",
        endpoint="admin_toggle_resource",
        view_func=admin_toggle_resource,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/recursos/<int:resource_id>/estado",
        endpoint="admin_toggle_resource",
        view_func=admin_toggle_resource,
        methods=["POST"],
    )

    # Admin conocimiento
    app.add_url_rule(
        "/admin/conocimiento",
        endpoint="admin_conocimiento",
        view_func=admin_conocimiento,
        methods=["GET"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/conocimiento",
        endpoint="admin_conocimiento",
        view_func=admin_conocimiento,
        methods=["GET"],
    )
    app.add_url_rule(
        "/admin/conocimiento/crear",
        endpoint="admin_conocimiento_crear",
        view_func=admin_conocimiento_crear,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/conocimiento/crear",
        endpoint="admin_conocimiento_crear",
        view_func=admin_conocimiento_crear,
        methods=["POST"],
    )
    app.add_url_rule(
        "/admin/conocimiento/<int:knowledge_id>/editar",
        endpoint="admin_conocimiento_editar",
        view_func=admin_conocimiento_editar,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/conocimiento/<int:knowledge_id>/editar",
        endpoint="admin_conocimiento_editar",
        view_func=admin_conocimiento_editar,
        methods=["POST"],
    )
    app.add_url_rule(
        "/admin/conocimiento/<int:knowledge_id>/eliminar",
        endpoint="admin_conocimiento_eliminar",
        view_func=admin_conocimiento_eliminar,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/conocimiento/<int:knowledge_id>/eliminar",
        endpoint="admin_conocimiento_eliminar",
        view_func=admin_conocimiento_eliminar,
        methods=["POST"],
    )

    # Admin conversaciones
    app.add_url_rule(
        "/admin/conversaciones",
        endpoint="admin_conversaciones",
        view_func=admin_conversaciones,
        methods=["GET"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/conversaciones",
        endpoint="admin_conversaciones",
        view_func=admin_conversaciones,
        methods=["GET"],
    )
    app.add_url_rule(
        "/admin/conversaciones/<int:session_id>",
        endpoint="admin_conversaciones_detalle",
        view_func=admin_conversaciones_detalle,
        methods=["GET"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/conversaciones/<int:session_id>",
        endpoint="admin_conversaciones_detalle",
        view_func=admin_conversaciones_detalle,
        methods=["GET"],
    )
    app.add_url_rule(
        "/admin/conversaciones/<int:session_id>/resolver",
        endpoint="admin_conversaciones_resolver",
        view_func=admin_conversaciones_resolver,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/conversaciones/<int:session_id>/resolver",
        endpoint="admin_conversaciones_resolver",
        view_func=admin_conversaciones_resolver,
        methods=["POST"],
    )
    app.add_url_rule(
        "/admin/conversaciones/<int:session_id>/estado",
        endpoint="admin_conversaciones_estado",
        view_func=admin_conversaciones_estado,
        methods=["POST"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/conversaciones/<int:session_id>/estado",
        endpoint="admin_conversaciones_estado",
        view_func=admin_conversaciones_estado,
        methods=["POST"],
    )

    # Admin inteligencia
    app.add_url_rule(
        "/admin/inteligencia",
        endpoint="admin_inteligencia",
        view_func=admin_inteligencia,
        methods=["GET"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/inteligencia",
        endpoint="admin_inteligencia",
        view_func=admin_inteligencia,
        methods=["GET"],
    )
    app.add_url_rule(
        "/admin/inteligencia/oportunidades",
        endpoint="admin_inteligencia_oportunidades",
        view_func=admin_inteligencia_oportunidades,
        methods=["GET"],
    )
    app.add_url_rule(
        "/b/<slug>/admin/inteligencia/oportunidades",
        endpoint="admin_inteligencia_oportunidades",
        view_func=admin_inteligencia_oportunidades,
        methods=["GET"],
    )