"""Migrador SQLite → PostgreSQL (Fase 5A — migrador de datos controlado).

Lee datos de una base SQLite existente, los transforma según el mapeo de tipos
definido en ``migrations_pg/001_initial_schema.sql`` y los inserta en una base
PostgreSQL vacía, preservando IDs y foreign keys.

Características:
    - Preserva IDs existentes (GENERATED BY DEFAULT permite INSERT explícito).
    - No copia índices SQLite (el esquema PostgreSQL ya define los suyos).
    - No copia tablas FTS5 de SQLite (PostgreSQL usa tsvector+GIN, GENERATED).
    - Maneja conversiones: INTEGER, BOOLEAN(0/1→true/false), DATE, TIME,
      TIMESTAMPTZ, TEXT, NULL.
    - Transaccional en PostgreSQL: un error en cualquier tabla hace rollback
      completo de la transacción de inserción.
    - Modo DRY-RUN: valida y reporta sin escribir.
    - Idempotencia: si la BD destino ya contiene datos, se rechaza explícitamente.
    - Ajusta sequences al MAX(id) tras la inserción.
    - Reconstruye document_tsearch (GENERATED STORED) automáticamente al insertar.
"""

from __future__ import annotations

import dataclasses
import datetime
import logging
import sqlite3
import time
from pathlib import Path
from typing import Any

import psycopg

logger = logging.getLogger("turnobot.migrator")

BASE_DIR = Path(__file__).resolve().parent.parent

SQLITE_MIGRATIONS_DIR = BASE_DIR / "migrations"
PG_SCHEMA_PATH = BASE_DIR / "migrations_pg" / "001_initial_schema.sql"

SKIP_TABLES = frozenset(
    {
        "schema_version",
        "migration_log",
        "sqlite_sequence",
        "business_knowledge_fts",
        "business_knowledge_fts_data",
        "business_knowledge_fts_idx",
        "business_knowledge_fts_config",
        "business_knowledge_fts_docsize",
        "business_knowledge_fts_vocab",
    }
)

# Tablas cuyos datos son considerados "seed" del esquema PostgreSQL y no deben
# fallar la verificación de BD vacía. El esquema PostgreSQL sembró los roles al
# inicializar; no son datos migrados.
SEED_TABLES = frozenset({"roles"})

# Orden de migración: respetar dependency order para FKs.
MIGRATION_TABLE_ORDER = [
    "businesses",
    "roles",
    "users",
    "business_settings",
    "weekly_schedules",
    "services",
    "resources",
    "appointments",
    "business_users",
    "sessions",
    "platform_users",
    "platform_sessions",
    "audit_log",
    "invitations",
    "notification_log",
    "loyalty_settings",
    "loyalty_accounts",
    "rewards",
    "points_ledger",
    "redemptions",
    "retention_actions",
    "business_knowledge",
    "conversation_sessions",
    "conversation_messages",
    "conversation_analytics",
    "password_reset_tokens",
]


@dataclasses.dataclass
class TableMigrationResult:
    """Resultado de la migración de una tabla."""

    table_name: str
    rows_read: int
    rows_inserted: int
    rows_skipped: int = 0
    error: str | None = None
    duration_seconds: float = 0.0


@dataclasses.dataclass
class MigrationReport:
    """Reporte completo de la migración."""

    dry_run: bool
    total_tables: int
    tables_migrated: int
    total_rows_read: int
    total_rows_inserted: int
    total_rows_skipped: int
    table_results: list[TableMigrationResult]
    errors: list[str]
    started_at: float
    finished_at: float
    source_db_path: str
    target_conninfo: str

    @property
    def duration_seconds(self) -> float:
        return round(self.finished_at - self.started_at, 3)

    @property
    def success(self) -> bool:
        return len(self.errors) == 0


class MigrationError(Exception):
    """Error durante la migración de datos."""


class MigrationTargetNotEmptyError(Exception):
    """La BD destino ya contiene datos: se rechaza para evitar duplicación."""


def _open_sqlite_readonly(db_path: str | Path) -> sqlite3.Connection:
    """Abre una conexión SQLite en modo read-only (no bloquea, no modifica)."""
    path = str(Path(db_path).resolve())
    if not Path(path).exists():
        raise FileNotFoundError(f"Base SQLite no encontrada: {path}")
    uri = f"file:{path}?mode=ro"
    conn = sqlite3.connect(uri, uri=True, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    return conn


def _sqlite_table_exists(conn: sqlite3.Connection, table_name: str) -> bool:
    """Verifica si una tabla existe en SQLite (excluye tablas internas)."""
    row = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name = ?", (table_name,)
    ).fetchone()
    return row is not None


def _get_generated_columns_pg(conn: psycopg.Connection, table_name: str) -> set[str]:
    """Descubre columnas GENERATED de PostgreSQL (no se deben INSERTar).

    PostgreSQL 16 expone ``is_generated`` en ``information_schema.columns``
    con valores 'NEVER', 'ALWAYS', 'STORED'. Las columnas GENERATED ALWAYS
    o GENERATED BY DEFAULT se detectan filtrando donde ``is_generated != 'NEVER'``.
    """
    rows = conn.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = %s
          AND is_generated = 'ALWAYS'
        """,
        (table_name,),
    ).fetchall()
    return {row[0] for row in rows}


def _get_column_types_pg(conn: psycopg.Connection, table_name: str) -> dict[str, str]:
    """Obtiene el data_type de cada columna de una tabla PostgreSQL."""
    rows = conn.execute(
        """
        SELECT column_name, data_type
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = %s
        """,
        (table_name,),
    ).fetchall()
    return {row[0]: row[1] for row in rows}


def _convert_value(value: Any, pg_type: str | None) -> Any:
    """Convierte un valor SQLite al tipo compatible con PostgreSQL.

    - INTEGER (0/1) -> BOOLEAN cuando pg_type es 'boolean'.
    - TEXT 'YYYY-MM-DD' -> datetime.date cuando pg_type es 'date'.
    - TEXT 'HH:MM' -> datetime.time cuando pg_type es 'time without time zone'.
    - TEXT 'YYYY-MM-DD HH:MM:SS' -> datetime.datetime con tzinfo UTC cuando
      pg_type es 'timestamp with time zone'.
    - None pasa a través sin cambios.
    """
    if value is None:
        return None

    if pg_type == "boolean" and isinstance(value, int):
        return bool(value)

    if pg_type == "date" and isinstance(value, str):
        return datetime.date.fromisoformat(value)

    if pg_type == "time without time zone" and isinstance(value, str):
        return datetime.time.fromisoformat(value)

    if pg_type == "timestamp with time zone" and isinstance(value, str):
        dt = datetime.datetime.fromisoformat(value)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=datetime.UTC)
        return dt

    return value


def _get_user_columns_sqlite(conn: sqlite3.Connection, table_name: str) -> list[str]:
    """Obtiene las columnas de una tabla SQLite (excluyendo rowid virtual)."""
    rows = conn.execute(f"PRAGMA table_info({table_name})").fetchall()
    return [row["name"] for row in rows]


def _get_user_columns_pg(conn: psycopg.Connection, table_name: str) -> list[str]:
    """Obtiene las columnas de una tabla PostgreSQL.

    Si la tabla no existe en PG, lanza MigrationError — una tabla en table_order
    que no existe en el esquema PG es un error de configuración, no un skip.
    """
    rows = conn.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = %s
        ORDER BY ordinal_position
        """,
        (table_name,),
    ).fetchall()
    if not rows:
        raise MigrationError(f"Tabla no existe en PostgreSQL: {table_name}")
    return [row[0] for row in rows]


def _table_has_data_pg(conn: psycopg.Connection, table_name: str) -> bool:
    """Verifica si una tabla PostgreSQL tiene datos.

    Si la tabla no existe (UndefinedTable), retorna False: la tabla no tiene
    datos migrables, pero no debe abortar el chequeo de otras tablas.
    """
    try:
        row = conn.execute(f'SELECT COUNT(*) FROM "{table_name}"').fetchone()
        return (row[0] if row else 0) > 0
    except psycopg.errors.UndefinedTable:
        conn.rollback()
        return False


def _check_target_not_empty(conn: psycopg.Connection, table_names: list[str]) -> list[str]:
    """Verifica que ninguna tabla de migración tenga datos previos (excepto seeds).

    Las tablas en SEED_TABLES (ej. roles) son pobladas por el esquema PostgreSQL
    al inicializar, no por el migrador. Se excluyen de la verificación.

    Returns: lista de nombres de tablas que YA tienen datos migrables.
    """
    non_empty: list[str] = []
    for table_name in table_names:
        if table_name in SEED_TABLES:
            continue
        if _table_has_data_pg(conn, table_name):
            non_empty.append(table_name)
    return non_empty


def _build_insert_sql(table_name: str, columns: list[str]) -> str:
    """Construye un INSERT ... VALUES con placeholders %s para psycopg3."""
    placeholders = ", ".join(["%s"] * len(columns))
    cols_str = ", ".join(f'"{c}"' for c in columns)
    return f'INSERT INTO "{table_name}" ({cols_str}) VALUES ({placeholders})'


def _migrate_table(
    sqlite_conn: sqlite3.Connection,
    pg_conn: psycopg.Connection,
    table_name: str,
    batch_size: int = 500,
) -> TableMigrationResult:
    """Migra una tabla desde SQLite hacia PostgreSQL.

    - Lee filas en batches para manejar bases grandes con memoria limitada.
    - Preserva IDs.
    - Convierte tipos (psycopg3 adapta automáticamente bool/int/datetime/str).
    - Transaccional: dentro de la transacción PG del caller, si falla un batch,
      el error se propaga y el caller hace rollback total.
    """
    result = TableMigrationResult(
        table_name=table_name, rows_read=0, rows_inserted=0, rows_skipped=0, duration_seconds=0.0
    )

    start = time.monotonic()

    sqlite_cols = _get_user_columns_sqlite(sqlite_conn, table_name)
    pg_cols = _get_user_columns_pg(pg_conn, table_name)
    pg_types = _get_column_types_pg(pg_conn, table_name)
    generated_cols = _get_generated_columns_pg(pg_conn, table_name)

    columns_to_migrate = [c for c in sqlite_cols if c in pg_cols and c not in generated_cols]

    if not columns_to_migrate:
        result.duration_seconds = round(time.monotonic() - start, 3)
        return result

    insert_sql = _build_insert_sql(table_name, columns_to_migrate)

    try:
        offset = 0
        while True:
            rows = sqlite_conn.execute(
                f'SELECT {", ".join(columns_to_migrate)} FROM "{table_name}" '
                f"LIMIT {batch_size} OFFSET {offset}"
            ).fetchall()

            if not rows:
                break

            result.rows_read += len(rows)

            values_list: list[list[Any]] = []
            for row in rows:
                row_dict = dict(zip(columns_to_migrate, row))
                values_list.append(
                    [_convert_value(row_dict[col], pg_types.get(col)) for col in columns_to_migrate]
                )

            try:
                with pg_conn.cursor() as cur:
                    cur.executemany(insert_sql, values_list)
                result.rows_inserted += len(rows)
            except Exception as e:
                result.error = f"Error insertando en {table_name} (offset {offset}): {e}"
                raise

            offset += batch_size

        result.duration_seconds = round(time.monotonic() - start, 3)
    except Exception as e:
        result.duration_seconds = round(time.monotonic() - start, 3)
        result.error = str(e)
        raise

    return result


def _reset_sequences_pg(conn: psycopg.Connection, table_names: list[str]) -> list[str]:
    """Ajusta las sequences de PostgreSQL al MAX(id) de cada tabla.

    Para tablas generadas con IDENTITY, la sequence asociada se obtiene de
    ``pg_get_serial_sequence``. Después de insertar IDs explícitos, la sequence
    debe avanzar al MAX(id) + 1 para que futuros INSERT no colisionen.
    """
    messages: list[str] = []
    for table_name in table_names:
        try:
            seq_result = conn.execute(
                f"SELECT pg_get_serial_sequence('{table_name}', 'id')"
            ).fetchone()
            if seq_result and seq_result[0]:
                seq_name = seq_result[0]
                max_id_result = conn.execute(f'SELECT MAX("id") FROM "{table_name}"').fetchone()
                max_id = max_id_result[0] if max_id_result else None
                if max_id is not None:
                    conn.execute(f"SELECT setval('{seq_name}', %s, true)", (int(max_id),))
                    messages.append(f"Secuencia {seq_name} ajustada a MAX(id)={max_id}")
                else:
                    messages.append(f"Tabla {table_name} vacía; secuencia no ajustada")
            else:
                messages.append(f"Tabla {table_name}: sin sequence (posiblemente no usa IDENTITY)")
        except Exception as e:
            messages.append(f"Error ajustando sequence para {table_name}: {e}")
    return messages


def _verify_foreign_keys_pg(conn: psycopg.Connection) -> list[str]:
    """Verifica que todas las foreign keys de la BD sean consistentes.

    PostgreSQL valida FKs durante el INSERT; si el migrador completó sin errores,
    las FKs ya están consistentes. Esta función realiza una verificación
    explícita post-migración como doble chequeo.
    """
    problems: list[str] = []
    fk_constraints = conn.execute(
        """
        SELECT conname, conrelid::regclass AS table_name
        FROM pg_constraint
        WHERE contype = 'f'
          AND connamespace = 'public'::regnamespace
        """
    ).fetchall()
    for conname, table_name in fk_constraints:
        try:
            conn.execute(f'ALTER TABLE "{table_name}" VALIDATE CONSTRAINT "{conname}"')
        except Exception as e:
            problems.append(f"FK {conname} en {table_name}: {e}")
    return problems


def migrate_sqlite_to_postgres(
    sqlite_db_path: str | Path,
    pg_conninfo: str,
    *,
    dry_run: bool = False,
    batch_size: int = 500,
    table_order: list[str] | None = None,
) -> MigrationReport:
    """Migra datos desde SQLite hacia PostgreSQL.

    Args:
        sqlite_db_path: Ruta al archivo SQLite (.db).
        pg_conninfo: Connection string psycopg3 (URL o key/value).
        dry_run: Si True, valida y reporta sin modificar PostgreSQL.
        batch_size: Tamaño de lote para lecturas/escrituras.
        table_order: Orden explícito de tablas (default: MIGRATION_TABLE_ORDER).

    Returns:
        MigrationReport con resultados detallados.

    Raises:
        MigrationTargetNotEmptyError: Si alguna tabla destino ya tiene datos.
        MigrationError: Si falla la migración (rollback automático en PG).
    """
    started_at = time.monotonic()
    tables = table_order if table_order is not None else list(MIGRATION_TABLE_ORDER)

    report = MigrationReport(
        dry_run=dry_run,
        total_tables=len(tables),
        tables_migrated=0,
        total_rows_read=0,
        total_rows_inserted=0,
        total_rows_skipped=0,
        table_results=[],
        errors=[],
        started_at=started_at,
        finished_at=0.0,
        source_db_path=str(sqlite_db_path),
        target_conninfo=pg_conninfo,
    )

    sqlite_conn = _open_sqlite_readonly(sqlite_db_path)

    try:
        pg_conn = psycopg.connect(pg_conninfo, autocommit=dry_run)

        try:
            tables = [t for t in tables if _sqlite_table_exists(sqlite_conn, t)]
            non_empty = _check_target_not_empty(pg_conn, tables)
            if non_empty:
                raise MigrationTargetNotEmptyError(
                    f"La BD destino ya contiene datos en: {', '.join(non_empty)}. "
                    f"Use una BD destino vacía o limpie los datos antes de migrar."
                )

            if dry_run:
                logger.info("Modo DRY-RUN: no se modificarán datos en PostgreSQL.")
                for table_name in tables:
                    if table_name in SEED_TABLES:
                        result = TableMigrationResult(
                            table_name=table_name,
                            rows_read=0,
                            rows_inserted=0,
                            rows_skipped=0,
                            error=None,
                        )
                        report.table_results.append(result)
                        logger.info("Tabla %s omitida (seed del esquema PG).", table_name)
                        continue
                    try:
                        row = sqlite_conn.execute(f'SELECT COUNT(*) FROM "{table_name}"').fetchone()
                        count = row[0] if row else 0
                        report.total_rows_read += count
                        result = TableMigrationResult(
                            table_name=table_name,
                            rows_read=count,
                            rows_inserted=count,
                            rows_skipped=0,
                        )
                        report.table_results.append(result)
                        report.tables_migrated += 1
                    except sqlite3.OperationalError as e:
                        if "no such table" in str(e).lower():
                            result = TableMigrationResult(
                                table_name=table_name,
                                rows_read=0,
                                rows_inserted=0,
                                rows_skipped=0,
                                error=f"Tabla no existe en SQLite: {table_name}",
                            )
                            report.table_results.append(result)
                            report.errors.append(f"{table_name}: {result.error}")
                        else:
                            raise
            else:
                pg_conn.execute("BEGIN")
                try:
                    for table_name in tables:
                        if table_name in SEED_TABLES:
                            result = TableMigrationResult(
                                table_name=table_name,
                                rows_read=0,
                                rows_inserted=0,
                                rows_skipped=0,
                                error=None,
                            )
                            report.table_results.append(result)
                            logger.info("Tabla %s omitida (seed del esquema PG).", table_name)
                            continue
                        try:
                            result = _migrate_table(
                                sqlite_conn, pg_conn, table_name, batch_size=batch_size
                            )
                            report.table_results.append(result)
                            if result.rows_read > 0:
                                report.tables_migrated += 1
                            report.total_rows_read += result.rows_read
                            report.total_rows_inserted += result.rows_inserted
                            report.total_rows_skipped += result.rows_skipped
                        except sqlite3.OperationalError as e:
                            if "no such table" in str(e).lower():
                                result = TableMigrationResult(
                                    table_name=table_name,
                                    rows_read=0,
                                    rows_inserted=0,
                                    rows_skipped=0,
                                    error=f"Tabla no existe en SQLite: {table_name}",
                                )
                                report.table_results.append(result)
                                report.errors.append(f"{table_name}: {result.error}")
                                raise MigrationError(
                                    f"Tabla no existe en SQLite: {table_name}"
                                ) from e
                            raise

                    seq_messages = _reset_sequences_pg(pg_conn, tables)
                    for msg in seq_messages:
                        logger.debug("Sequence: %s", msg)

                    fk_problems = _verify_foreign_keys_pg(pg_conn)
                    if fk_problems:
                        raise MigrationError(f"Problemas de integridad de FKs: {fk_problems}")

                    pg_conn.commit()
                    logger.info(
                        "Migración completada: %d tablas, %d filas",
                        report.tables_migrated,
                        report.total_rows_inserted,
                    )
                except Exception as e:
                    pg_conn.rollback()
                    logger.error("Migración falló, rollback completo: %s", e)
                    report.errors.append(f"Rollback ejecutado. Error original: {e}")
                    raise MigrationError(f"Migración falló y fue revertida: {e}") from e
        finally:
            pg_conn.close()

    finally:
        sqlite_conn.close()

    report.finished_at = time.monotonic()
    return report
