-- ============================================================================
-- FASE 4E - ESQUEMA POSTGRESQL FINAL PARA TURNOBOT
-- ============================================================================
-- DDL PostgreSQL equivalente al estado final del schema SQLite definido por
-- las 22 migraciones en migrations/ (001..022). Ejecutable desde cero.
--
-- Mapeo SQLite -> PostgreSQL (decisiones documentadas de Fase 4E):
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS
--     IDENTITY PRIMARY KEY (permite IDs explicitos durante un futuro ETL).
--   * TEXT -> TEXT. Unico REAL monetario (services.price) -> NUMERIC(10,2).
--   * Flags 0/1 demostrados como flags por las migraciones -> BOOLEAN.
--   * Fechas 'YYYY-MM-DD' -> DATE. Horas 'HH:MM' -> TIME.
--   * Timestamps TEXT 'YYYY-MM-DD HH:MM:SS' (CURRENT_TIMESTAMP / datetime('now'))
--     -> TIMESTAMPTZ.
--   * DEFAULT '' de columnas temporales migradas en SQLite (artefacto de
--     ADD COLUMN sobre datos existentes, ej. businesses.created_at) -> no se
--     propaga; se usa el valor representativo (CURRENT_TIMESTAMP o NULL).
--   * CHECK con dominio real conservados (points_cost>0, action_type IN,
--     status IN, role IN, type IN). CHECK de dominio binario (active IN (0,1),
--     revoked IN (0,1)) absorbidos por el tipo BOOLEAN.
--   * UNIQUE simples/compuestos, indices e indices parciales reproducidos 1:1,
--     incluida la semantica final de 022 (COALESCE(resource_id, -1)).
--   * FK con ON DELETE CASCADE / SET NULL exactos.
--   * Semilla estructural UNICAMENTE: roles (owner/admin/staff/customer),
--     requeridos por FK y por la logica de autorizacion.
--   * EXCLUIDOS (no trasladables a PostgreSQL o fuera de migrations/):
--       - business_knowledge_fts (tabla virtual FTS5) y sus triggers
--         bk_fts_ai / bk_fts_ad / bk_fts_au. La busqueda FTS es una fase
--         posterior (tsvector/GIN) fuera del alcance de 4E.
--       - schema_version / migration_log (tablas internas del runner SQLite).
--       - sqlite_sequence (interna de SQLite).
-- ============================================================================

BEGIN;

-- ============================================================================
-- NEGOCIOS
-- ============================================================================
CREATE TABLE businesses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    slug       TEXT NOT NULL UNIQUE,
    -- 012: ADD COLUMN active INTEGER NOT NULL DEFAULT 1 (flag 0/1).
    active     BOOLEAN NOT NULL DEFAULT TRUE,
    -- 013: ADD COLUMN pending INTEGER NOT NULL DEFAULT 1 (luego UPDATE 0).
    pending    BOOLEAN NOT NULL DEFAULT TRUE,
    -- 012: ADD COLUMN TEXT NOT NULL DEFAULT '' (artefacto legacy; app inserta
    -- datetime('now')). Equivalente CURRENT_TIMESTAMP.
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- ROLES (semilla estructural)
-- ============================================================================
CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

-- 005: seed de roles base (requeridos por FK y autorizacion).
INSERT INTO roles (id, name) VALUES
    (1, 'owner'),
    (2, 'admin'),
    (3, 'staff'),
    (4, 'customer')
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- USUARIOS DE NEGOCIO
-- ============================================================================
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- CONFIGURACION DEL NEGOCIO
-- 007 elimina el CHECK (id = 1) heredado de 001.
-- 008 notifications_enabled. 013 notification_email. 018 branding.
-- ============================================================================
CREATE TABLE business_settings (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_name       TEXT NOT NULL DEFAULT 'Mi negocio',
    slot_duration       INTEGER NOT NULL DEFAULT 60,
    break_between_slots INTEGER NOT NULL DEFAULT 0,
    business_type       TEXT NOT NULL DEFAULT 'Barberia',
    business_initials   TEXT NOT NULL DEFAULT 'EC',
    business_description TEXT NOT NULL DEFAULT 'Barberia masculina',
    timezone            TEXT NOT NULL DEFAULT 'America/Argentina/Buenos_Aires',
    business_id         BIGINT NOT NULL UNIQUE REFERENCES businesses(id),
    notifications_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    notification_email  TEXT NOT NULL DEFAULT '',
    logo_url            TEXT NOT NULL DEFAULT '',
    primary_color       TEXT NOT NULL DEFAULT '',
    secondary_color     TEXT NOT NULL DEFAULT ''
);

-- ============================================================================
-- HORARIOS SEMANALES (0=lun, 6=dom)
-- ============================================================================
CREATE TABLE weekly_schedules (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week    INTEGER NOT NULL,
    is_open        BOOLEAN NOT NULL DEFAULT FALSE,
    morning_start  TIME,
    morning_end    TIME,
    afternoon_start TIME,
    afternoon_end  TIME,
    business_id    BIGINT NOT NULL REFERENCES businesses(id),
    UNIQUE (business_id, day_of_week)
);

CREATE INDEX idx_schedules_business ON weekly_schedules (business_id);

-- ============================================================================
-- SERVICIOS
-- ============================================================================
CREATE TABLE services (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    price       NUMERIC(10,2) NOT NULL DEFAULT 0,
    duration    INTEGER NOT NULL DEFAULT 60,
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    business_id BIGINT NOT NULL REFERENCES businesses(id)
);

CREATE INDEX idx_services_business ON services (business_id);

-- ============================================================================
-- RECURSOS RESERVABLES (015)
-- ============================================================================
CREATE TABLE resources (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (business_id, name)
);

CREATE INDEX idx_resources_business ON resources (business_id);

-- ============================================================================
-- TURNOS
-- ============================================================================
CREATE TABLE appointments (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name        TEXT NOT NULL,
    phone                TEXT,
    customer_email       TEXT,
    service              TEXT NOT NULL,
    appointment_date     DATE NOT NULL,
    appointment_time     TIME NOT NULL,
    appointment_end      TIME NOT NULL,
    duration             INTEGER NOT NULL,
    status               TEXT NOT NULL DEFAULT 'confirmed',
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    business_id          BIGINT NOT NULL REFERENCES businesses(id),
    management_token_hash TEXT,
    resource_id          BIGINT REFERENCES resources(id)
);

-- 022 (estado final): UNIQUE parcial con COALESCE(resource_id, -1); reemplaza
-- los dos indices parciales de 015.
CREATE UNIQUE INDEX unique_confirmed_appointment_slot
ON appointments (business_id, appointment_date, appointment_time, COALESCE(resource_id, -1))
WHERE status = 'confirmed';

CREATE INDEX idx_appointments_phone ON appointments (phone);
CREATE INDEX idx_appointments_date_status ON appointments (appointment_date, status);
CREATE INDEX idx_appointments_status ON appointments (status);
CREATE INDEX idx_appointments_business ON appointments (business_id);
CREATE INDEX idx_appointments_management_token ON appointments (management_token_hash);

-- ============================================================================
-- RELACION USUARIO <-> NEGOCIO (N:N con rol)
-- ============================================================================
CREATE TABLE business_users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id),
    business_id BIGINT NOT NULL REFERENCES businesses(id),
    role_id     BIGINT NOT NULL REFERENCES roles(id),
    UNIQUE (user_id, business_id)
);

CREATE INDEX idx_business_users_business ON business_users (business_id);
CREATE INDEX idx_business_users_user ON business_users (user_id);

-- ============================================================================
-- SESIONES DE USUARIOS DE NEGOCIO
-- ============================================================================
CREATE TABLE sessions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    token_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked    BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_sessions_user ON sessions (user_id);

-- ============================================================================
-- PLATAFORMA (SUPERADMIN): 012
-- ============================================================================
CREATE TABLE platform_users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT NOT NULL UNIQUE,
    display_name  TEXT NOT NULL DEFAULT '',
    password_hash TEXT NOT NULL,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE platform_sessions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_user_id BIGINT NOT NULL REFERENCES platform_users(id) ON DELETE CASCADE,
    token_hash       TEXT NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at       TIMESTAMPTZ NOT NULL,
    revoked          BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_platform_sessions_user ON platform_sessions (platform_user_id);

CREATE TABLE audit_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_user_id BIGINT REFERENCES platform_users(id) ON DELETE SET NULL,
    actor_email      TEXT NOT NULL DEFAULT '',
    business_id      BIGINT REFERENCES businesses(id) ON DELETE SET NULL,
    action           TEXT NOT NULL,
    detail           TEXT NOT NULL DEFAULT '',
    ip_address       TEXT NOT NULL DEFAULT '',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_log_business_created ON audit_log (business_id, created_at);
CREATE INDEX idx_audit_log_action ON audit_log (action, created_at);

-- ============================================================================
-- INVITACIONES DE OWNER (012 + 014 revoked_at)
-- ============================================================================
CREATE TABLE invitations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_name   TEXT NOT NULL DEFAULT 'owner',
    email       TEXT NOT NULL,
    token_hash  TEXT NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    used_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at  TIMESTAMPTZ
);

CREATE INDEX idx_invitations_business ON invitations (business_id, created_at);
CREATE INDEX idx_invitations_user ON invitations (user_id);

-- ============================================================================
-- LOG DE NOTIFICACIONES (008 + 013 status/error/last_attempt_at + 014 claimed_at)
-- ============================================================================
CREATE TABLE notification_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL REFERENCES appointments(id),
    business_id    BIGINT NOT NULL REFERENCES businesses(id),
    type           TEXT NOT NULL,
    channel        TEXT NOT NULL DEFAULT 'email',
    destination    TEXT NOT NULL DEFAULT '',
    sent_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status         TEXT NOT NULL DEFAULT 'sent',
    error          TEXT NOT NULL DEFAULT '',
    -- 013: TEXT NOT NULL DEFAULT ''. El default '' equivalia a "sin intento
    --      aun"; se representa como NULL (TIMESTAMPTZ nullable).
    last_attempt_at TIMESTAMPTZ,
    claimed_at     TIMESTAMPTZ
);

CREATE UNIQUE INDEX idx_notification_log_unique
ON notification_log (business_id, appointment_id, type, channel);

CREATE INDEX idx_notification_log_business ON notification_log (business_id);

-- ============================================================================
-- FIDELIZACION (009 + 010)
-- ============================================================================
CREATE TABLE loyalty_settings (
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id                      BIGINT NOT NULL UNIQUE REFERENCES businesses(id),
    enabled                          BOOLEAN NOT NULL DEFAULT FALSE,
    points_per_completed_appointment INTEGER NOT NULL DEFAULT 1,
    created_at                       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_loyalty_settings_business ON loyalty_settings (business_id);

CREATE TABLE loyalty_accounts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id   BIGINT NOT NULL REFERENCES businesses(id),
    customer_phone TEXT NOT NULL,
    customer_email TEXT,
    customer_name TEXT,
    points_balance INTEGER NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (business_id, customer_phone)
);

CREATE INDEX idx_loyalty_accounts_business_balance
ON loyalty_accounts (business_id, points_balance DESC);

CREATE TABLE rewards (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    description TEXT,
    points_cost INTEGER NOT NULL CHECK (points_cost > 0),
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (business_id, name)
);

CREATE TABLE redemptions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id     BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    account_id      BIGINT NOT NULL REFERENCES loyalty_accounts(id) ON DELETE CASCADE,
    reward_id       BIGINT NOT NULL REFERENCES rewards(id) ON DELETE CASCADE,
    points_used     INTEGER NOT NULL CHECK (points_used > 0),
    status          TEXT NOT NULL DEFAULT 'redeemed'
                    CHECK (status IN ('redeemed', 'cancelled')),
    idempotency_key TEXT NOT NULL,
    actor_user_id   BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (business_id, idempotency_key)
);

CREATE INDEX idx_redemptions_business_created ON redemptions (business_id, created_at);
CREATE INDEX idx_redemptions_account ON redemptions (account_id, created_at);

CREATE TABLE points_ledger (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id           BIGINT NOT NULL REFERENCES businesses(id),
    account_id            BIGINT NOT NULL REFERENCES loyalty_accounts(id),
    delta                 INTEGER NOT NULL,
    type                  TEXT NOT NULL,
    reason                TEXT NOT NULL DEFAULT '',
    appointment_id        BIGINT REFERENCES appointments(id),
    points_per_completed  INTEGER,
    actor_user_id         BIGINT REFERENCES users(id),
    reward_id             BIGINT REFERENCES rewards(id),
    -- Sin FK declarada en SQLite (010); se preserva como numerico nullable.
    redemption_id         BIGINT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Idempotencia: un turno completado solo acredita UNA vez por tenant.
CREATE UNIQUE INDEX idx_points_ledger_earn_per_appointment
ON points_ledger (business_id, appointment_id)
WHERE type = 'earn' AND appointment_id IS NOT NULL;

CREATE INDEX idx_points_ledger_account ON points_ledger (account_id, id);
CREATE INDEX idx_points_ledger_business_created ON points_ledger (business_id, created_at);

-- ============================================================================
-- TRAZABILIDAD DE ACCIONES DE RETENCION (011)
-- ============================================================================
CREATE TABLE retention_actions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id         BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    customer_phone      TEXT NOT NULL,
    action_type         TEXT NOT NULL CHECK (action_type IN ('viewed', 'contacted', 'skipped')),
    notes               TEXT,
    actor_user_id       BIGINT REFERENCES users(id) ON DELETE SET NULL,
    last_completed_date DATE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_retention_actions_business_created
ON retention_actions (business_id, created_at);

CREATE INDEX idx_retention_actions_phone
ON retention_actions (business_id, customer_phone, created_at);

-- ============================================================================
-- BASE DE CONOCIMIENTO (016) - SIN FTS
-- La tabla virtual FTS5 (business_knowledge_fts) y sus triggers se excluyen:
-- la busqueda vectorial es fase posterior (tsvector/GIN).
-- ============================================================================
CREATE TABLE business_knowledge (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id        BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    type               TEXT NOT NULL CHECK (type IN ('faq', 'instruction', 'policy')),
    question           TEXT NOT NULL,
    answer             TEXT NOT NULL,
    tags               TEXT,
    active             BOOLEAN NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id BIGINT REFERENCES users(id)
);

CREATE INDEX idx_bk_business_type ON business_knowledge (business_id, type);
CREATE INDEX idx_bk_business_active ON business_knowledge (business_id, active);

-- ============================================================================
-- CONVERSACIONES Y ESCALAMIENTO HUMANO (017 + 019 public_token)
-- ============================================================================
CREATE TABLE conversation_sessions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id        BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    customer_phone     TEXT NOT NULL,
    customer_name      TEXT,
    customer_email     TEXT,
    status             TEXT NOT NULL DEFAULT 'active',
    needs_human        BOOLEAN NOT NULL DEFAULT FALSE,
    human_requested_at TIMESTAMPTZ,
    resolved_at        TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    public_token       TEXT,
    UNIQUE (business_id, customer_phone)
);

CREATE INDEX idx_conv_sessions_business_status
ON conversation_sessions (business_id, status);

CREATE INDEX idx_conv_sessions_business_phone
ON conversation_sessions (business_id, customer_phone);

CREATE UNIQUE INDEX idx_conv_sessions_public_token
ON conversation_sessions (public_token)
WHERE public_token IS NOT NULL;

CREATE TABLE conversation_messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT NOT NULL REFERENCES conversation_sessions(id) ON DELETE CASCADE,
    role        TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'human', 'system')),
    content     TEXT NOT NULL,
    needs_human BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_conv_messages_session ON conversation_messages (session_id, created_at);
CREATE INDEX idx_conv_messages_needs_human ON conversation_messages (session_id, needs_human);

CREATE TABLE conversation_analytics (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id        BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    question_hash      TEXT NOT NULL,
    question_text      TEXT NOT NULL,
    count              INTEGER NOT NULL DEFAULT 1,
    needs_human_count  INTEGER NOT NULL DEFAULT 0,
    last_seen_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (business_id, question_hash)
);

CREATE INDEX idx_conv_analytics_business ON conversation_analytics (business_id, count DESC);

-- ============================================================================
-- PASSWORD RESET (018)
-- ============================================================================
CREATE TABLE password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_password_reset_tokens_user ON password_reset_tokens (user_id);
CREATE INDEX idx_password_reset_tokens_hash ON password_reset_tokens (token_hash);

COMMIT;